select 'acpi_tables' as table_name;
.types select * from acpi_tables;
select 'apparmor_profiles' as table_name;
.types select * from apparmor_profiles;
select 'apt_sources' as table_name;
.types select * from apt_sources;
select 'arp_cache' as table_name;
.types select * from arp_cache;
select 'atom_packages' as table_name;
.types select * from atom_packages;
select 'augeas' as table_name;
.types select * from augeas;
select 'authorized_keys' as table_name;
.types select * from authorized_keys;
select 'block_devices' as table_name;
.types select * from block_devices;
select 'carbon_black_info' as table_name;
.types select * from carbon_black_info;
select 'carves' as table_name;
.types select * from carves;
select 'chrome_extensions' as table_name;
.types select * from chrome_extensions;
select 'cpu_time' as table_name;
.types select * from cpu_time;
select 'cpuid' as table_name;
.types select * from cpuid;
select 'crontab' as table_name;
.types select * from crontab;
select 'curl' as table_name;
.types select * from curl;
select 'curl_certificate' as table_name;
.types select * from curl_certificate;
select 'deb_packages' as table_name;
.types select * from deb_packages;
select 'device_file' as table_name;
.types select * from device_file;
select 'device_hash' as table_name;
.types select * from device_hash;
select 'device_partitions' as table_name;
.types select * from device_partitions;
select 'disk_encryption' as table_name;
.types select * from disk_encryption;
select 'dns_resolvers' as table_name;
.types select * from dns_resolvers;
select 'docker_container_labels' as table_name;
.types select * from docker_container_labels;
select 'docker_container_mounts' as table_name;
.types select * from docker_container_mounts;
select 'docker_container_networks' as table_name;
.types select * from docker_container_networks;
select 'docker_container_ports' as table_name;
.types select * from docker_container_ports;
select 'docker_container_processes' as table_name;
.types select * from docker_container_processes;
select 'docker_container_stats' as table_name;
.types select * from docker_container_stats;
select 'docker_containers' as table_name;
.types select * from docker_containers;
select 'docker_image_labels' as table_name;
.types select * from docker_image_labels;
select 'docker_image_layers' as table_name;
.types select * from docker_image_layers;
select 'docker_images' as table_name;
.types select * from docker_images;
select 'docker_info' as table_name;
.types select * from docker_info;
select 'docker_network_labels' as table_name;
.types select * from docker_network_labels;
select 'docker_networks' as table_name;
.types select * from docker_networks;
select 'docker_version' as table_name;
.types select * from docker_version;
select 'docker_volume_labels' as table_name;
.types select * from docker_volume_labels;
select 'docker_volumes' as table_name;
.types select * from docker_volumes;
select 'elf_dynamic' as table_name;
.types select * from elf_dynamic;
select 'elf_info' as table_name;
.types select * from elf_info;
select 'elf_sections' as table_name;
.types select * from elf_sections;
select 'elf_segments' as table_name;
.types select * from elf_segments;
select 'elf_symbols' as table_name;
.types select * from elf_symbols;
select 'etc_hosts' as table_name;
.types select * from etc_hosts;
select 'etc_protocols' as table_name;
.types select * from etc_protocols;
select 'etc_services' as table_name;
.types select * from etc_services;
select 'file' as table_name;
.types select * from file;
select 'file_events' as table_name;
.types select * from file_events;
select 'firefox_addons' as table_name;
.types select * from firefox_addons;
select 'groups' as table_name;
.types select * from groups;
select 'hardware_events' as table_name;
.types select * from hardware_events;
select 'hash' as table_name;
.types select * from hash;
select 'intel_me_info' as table_name;
.types select * from intel_me_info;
select 'interface_addresses' as table_name;
.types select * from interface_addresses;
select 'interface_details' as table_name;
.types select * from interface_details;
select 'iptables' as table_name;
.types select * from iptables;
select 'kernel_info' as table_name;
.types select * from kernel_info;
select 'kernel_modules' as table_name;
.types select * from kernel_modules;
select 'known_hosts' as table_name;
.types select * from known_hosts;
select 'last' as table_name;
.types select * from last;
select 'listening_ports' as table_name;
.types select * from listening_ports;
select 'lldp_neighbors' as table_name;
.types select * from lldp_neighbors;
select 'load_average' as table_name;
.types select * from load_average;
select 'logged_in_users' as table_name;
.types select * from logged_in_users;
select 'magic' as table_name;
.types select * from magic;
select 'md_devices' as table_name;
.types select * from md_devices;
select 'md_drives' as table_name;
.types select * from md_drives;
select 'md_personalities' as table_name;
.types select * from md_personalities;
select 'memory_array_mapped_addresses' as table_name;
.types select * from memory_array_mapped_addresses;
select 'memory_arrays' as table_name;
.types select * from memory_arrays;
select 'memory_device_mapped_addresses' as table_name;
.types select * from memory_device_mapped_addresses;
select 'memory_devices' as table_name;
.types select * from memory_devices;
select 'memory_error_info' as table_name;
.types select * from memory_error_info;
select 'memory_info' as table_name;
.types select * from memory_info;
select 'memory_map' as table_name;
.types select * from memory_map;
select 'mounts' as table_name;
.types select * from mounts;
select 'msr' as table_name;
.types select * from msr;
select 'npm_packages' as table_name;
.types select * from npm_packages;
select 'oem_strings' as table_name;
.types select * from oem_strings;
select 'opera_extensions' as table_name;
.types select * from opera_extensions;
select 'os_version' as table_name;
.types select * from os_version;
select 'osquery_events' as table_name;
.types select * from osquery_events;
select 'osquery_extensions' as table_name;
.types select * from osquery_extensions;
select 'osquery_flags' as table_name;
.types select * from osquery_flags;
select 'osquery_info' as table_name;
.types select * from osquery_info;
select 'osquery_packs' as table_name;
.types select * from osquery_packs;
select 'osquery_registry' as table_name;
.types select * from osquery_registry;
select 'osquery_schedule' as table_name;
.types select * from osquery_schedule;
select 'pci_devices' as table_name;
.types select * from pci_devices;
select 'platform_info' as table_name;
.types select * from platform_info;
select 'portage_keywords' as table_name;
.types select * from portage_keywords;
select 'portage_packages' as table_name;
.types select * from portage_packages;
select 'portage_use' as table_name;
.types select * from portage_use;
select 'process_envs' as table_name;
.types select * from process_envs;
select 'process_events' as table_name;
.types select * from process_events;
select 'process_file_events' as table_name;
.types select * from process_file_events;
select 'process_memory_map' as table_name;
.types select * from process_memory_map;
select 'process_namespaces' as table_name;
.types select * from process_namespaces;
select 'process_open_files' as table_name;
.types select * from process_open_files;
select 'process_open_pipes' as table_name;
.types select * from process_open_pipes;
select 'process_open_sockets' as table_name;
.types select * from process_open_sockets;
select 'processes' as table_name;
.types select * from processes;
select 'prometheus_metrics' as table_name;
.types select * from prometheus_metrics;
select 'python_packages' as table_name;
.types select * from python_packages;
select 'routes' as table_name;
.types select * from routes;
select 'rpm_package_files' as table_name;
.types select * from rpm_package_files;
select 'rpm_packages' as table_name;
.types select * from rpm_packages;
select 'selinux_events' as table_name;
.types select * from selinux_events;
select 'selinux_settings' as table_name;
.types select * from selinux_settings;
select 'shadow' as table_name;
.types select * from shadow;
select 'shared_memory' as table_name;
.types select * from shared_memory;
select 'shell_history' as table_name;
.types select * from shell_history;
select 'smart_drive_info' as table_name;
.types select * from smart_drive_info;
select 'smbios_tables' as table_name;
.types select * from smbios_tables;
select 'socket_events' as table_name;
.types select * from socket_events;
select 'ssh_configs' as table_name;
.types select * from ssh_configs;
select 'sudoers' as table_name;
.types select * from sudoers;
select 'suid_bin' as table_name;
.types select * from suid_bin;
select 'syslog_events' as table_name;
.types select * from syslog_events;
select 'system_controls' as table_name;
.types select * from system_controls;
select 'system_info' as table_name;
.types select * from system_info;
select 'time' as table_name;
.types select * from time;
select 'ulimit_info' as table_name;
.types select * from ulimit_info;
select 'uptime' as table_name;
.types select * from uptime;
select 'usb_devices' as table_name;
.types select * from usb_devices;
select 'user_events' as table_name;
.types select * from user_events;
select 'user_groups' as table_name;
.types select * from user_groups;
select 'user_ssh_keys' as table_name;
.types select * from user_ssh_keys;
select 'users' as table_name;
.types select * from users;
select 'yara' as table_name;
.types select * from yara;
select 'yara_events' as table_name;
.types select * from yara_events;
select 'yum_sources' as table_name;
.types select * from yum_sources;
